# 基础镜像
FROM  openjdk:17
# author
MAINTAINER mall

# 挂载目录
VOLUME /home/mall
# 创建目录
RUN mkdir -p /home/mall
# 指定路径
WORKDIR /home/mall
# 复制jar文件到路径
COPY ./jar/mall-visual-monitor.jar /home/mall/mall-visual-monitor.jar
# 启动系统服务
ENTRYPOINT ["java","-jar","mall-visual-monitor.jar"]